### ISSUE TITLE
Fast Reset sometimes doesn't work and will save normally.

### ISSUE THREAD

**Issue by ryanhormann** [jan-leila/FastReset#2]
When using fast reset, the mod sometimes saves the game, and it takes just as long as normally saving and quitting would. It's annoying when using this with a reset macro, as sometimes the macro will be half way through creating a world when the world is finished saving, resulting in the macro doing unwanted thing for me, like quitting the game, or changing settings.

**Comment by jan-leila** [comment]
thats being cause because the game still needs to close the files even if it isnt writing to them and sometimes depending on what your drive is doing that can take longer to do. I probably wont be fixing that because its going to be very hard to maintain and isnt a major issue
